#!/bin/bash
# validate-commit.sh — PreToolUse hook for Bash
# Denies `git commit` calls whose message contains AI-generation footers.
# Suggests a clean Conventional Commit message instead.
#
# Input (via stdin): JSON with shape { "tool_input": { "command": "..." } }
# Output: JSON to stderr with hookSpecificOutput.permissionDecision = "deny" + systemMessage
# Exit 2 = blocking decision.

set -euo pipefail

INPUT="$(cat)"

# Extract the command field. If jq is missing, fall back to grep.
if command -v jq >/dev/null 2>&1; then
  CMD="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty')"
else
  CMD="$(printf '%s' "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed -e 's/.*"command"[[:space:]]*:[[:space:]]*"//' -e 's/"$//')"
fi

# If this isn't a git commit, allow it (no output, exit 0).
case "$CMD" in
  *git\ commit*|*git\ -C\ *commit*) : ;;  # proceed to footer check
  *) exit 0 ;;
esac

# AI-footer patterns we forbid in commit messages.
# Matches the most common variants across CodeBuddy Code, Claude Code, and Copilot.
PATTERNS='Generated with CodeBuddy|Generated with Claude Code|Co-Authored-By:[[:space:]]*Claude|Co-Authored-By:[[:space:]]*Copilot|🤖 Generated|Generated by AI'

if printf '%s' "$CMD" | grep -qiE "$PATTERNS"; then
  MSG="Blocked: git commit message contains an AI-generation footer.

The raihan-toolkit enforces a strict no-AI-footer policy on job-hunt and public repos.

Rewrite your commit message as a clean Conventional Commit:
  <type>(<scope>): <subject>

    body (why, not what)

Types: feat | fix | docs | style | refactor | perf | test | chore | build | ci
Subject: ≤72 chars, imperative mood, lowercase first word, no trailing period.

Do NOT include:
  - 'Generated with ...'
  - 'Co-Authored-By: Claude/Copilot/...'
  - Any AI trailer

Re-run: git commit -m \"feat(scope): your subject\" -m \"optional body\""

  # Output deny decision as JSON to stderr, then exit 2.
  printf '{"hookSpecificOutput":{"permissionDecision":"deny","permissionDecisionReason":"AI-footer detected in commit message"},"systemMessage":%s}\n' \
    "$(printf '%s' "$MSG" | jq -Rs .)" >&2
  exit 2
fi

# No footer detected → allow.
exit 0
